/**
 * The web half of `app-icons.tsx`. A lucide `<svg>` takes `currentColor` from its parent on
 * web, so there is nothing to wrap: the components are lucide's own, under the same names.
 */
export {
  Activity,
  ArrowDown,
  BookOpen,
  Box,
  Clipboard,
  Columns2,
  CornerDownLeft,
  Cpu,
  Database,
  ExternalLink,
  Globe,
  LayoutDashboard,
  LayoutGrid,
  Link as LinkIcon,
  List,
  Menu,
  MessageSquare,
  Mic,
  MicOff,
  PanelLeft,
  Save,
  Send,
  Server,
  SlidersHorizontal,
  Smartphone,
  SquareCheck,
  SquareKanban,
  Terminal,
  Volume2,
  VolumeX,
  Wrench,
  Zap,
} from "lucide-react";
